// <auto-generated />
using System;
using Assignment_4_Movies.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Assignment_4_Movies.Migrations
{
    [DbContext(typeof(MovieFormContext))]
    [Migration("20220201035307_initi")]
    partial class initi
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Assignment_4_Movies.Models.Category", b =>
                {
                    b.Property<int>("category_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("category_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("category_id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            category_id = 1,
                            category_name = "Comedy"
                        },
                        new
                        {
                            category_id = 2,
                            category_name = "Action"
                        },
                        new
                        {
                            category_id = 3,
                            category_name = "Romance"
                        });
                });

            modelBuilder.Entity("Assignment_4_Movies.Models.MovieModel", b =>
                {
                    b.Property<int>("movie_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("category_id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("category_id1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lent_to")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("movie_id");

                    b.HasIndex("category_id1");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            movie_id = 1,
                            category_id = 1,
                            director = "Smartest Man",
                            edited = false,
                            lent_to = "",
                            notes = "",
                            rating = "PG",
                            title = "Hot Rod",
                            year = 2000
                        },
                        new
                        {
                            movie_id = 2,
                            category_id = 2,
                            director = "Cute Girl",
                            edited = true,
                            lent_to = "",
                            notes = "",
                            rating = "G",
                            title = "13 Going On 30",
                            year = 2002
                        },
                        new
                        {
                            movie_id = 3,
                            category_id = 3,
                            director = "Russo Brothers",
                            edited = false,
                            lent_to = "",
                            notes = "",
                            rating = "PG",
                            title = "SpiderMan No Way Home",
                            year = 2021
                        });
                });

            modelBuilder.Entity("Assignment_4_Movies.Models.MovieModel", b =>
                {
                    b.HasOne("Assignment_4_Movies.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("category_id1");
                });
#pragma warning restore 612, 618
        }
    }
}
